service: solving-marketing-attribution
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post