storeEvent:
  handler: src/handlers/segment/storeEvent.handler
  description: Store identify() and page() events in two tables
  events:
    - http: 'POST /events'
  environment:
    IDENTIFY_TABLE: ${env:IDENTIFY_TABLE}
    PAGE_TABLE: ${env:PAGE_TABLE}

trackUser:
  handler: src/handlers/segment/trackUser.handler
  events:
    - http: 'GET /segment/track/user/{id}'

## Fill in visitor sources (channel) or s
identifyUser:
  handler: src/handlers/segment/identifyUser.handler
  events:
    - http: 'GET /segment/identify/user/{id}'

identifyAnonymous:
  handler: src/handlers/segment/identifyAnonymous.handler
  events:
    - http: 'GET /segment/identify/anonymous/{id}'

## Do channel or sales attribution (based on segment key)
identifyAttribution:
  handler: src/handlers/segment/identifyAttribution.handler
  events:
    - http: 'POST /segment/identify/attribution'

