  storeEvent:
    handler: src/handlers/segment/storeEvent.handler
    events:
      - http: 'POST /events'
  identifyUser:
    handler: src/handlers/segment/identifyUser.handler
    events:
      - http: 'GET /segment/identify/user/{id}'
  trackAnonymous:
    handler: src/handlers/segment/trackAnonymous.handler
    events:
      - http: 'GET /segment/track/anonymous/{id}'
  trackUser:
    handler: src/handlers/segment/trackUser.handler
    events:
      - http: 'GET /segment/track/user/{id}'